title: Damien Mac Fhlannchaidh

description: >
  [**Damien Mac Fhlannchaidh**](https://www.linkedin.com/in/*) is a Software Engineer and Leadership in Ruby and Objective-C/Swift.
  
  I sometimes blog on [Medium](https://medium.com/@damocodes).
  
copyright: Damien Mac Fhlannchaidh

sass:
  sass_dir: assets/sass
  
url: "https://www.damienmacfhlannchaidh.com"
site.url: "https://www.damienmacfhlannchaidh.com"

disqus_shortname: 
facebook_username:
twitter_username: "damocodes"
linkedin_username: "*"
instagram_username:
pinterest_username: "*"
flickr_username: "*"
github_username:  "damienmacfhlannchaidh"
feed_icon: rss
email: "macfhlannchaidh@icloud.com"

plugins: [jekyll-paginate]

permalink: ":year/:month/:day/:title.html"
paginate_path: "/page/:num/"
paginate: 5
